set-threads:
    tenx2seuratrds: 1
    soupx: 1

set-resources:
    tenx2seuratrds:
        nodes: 1
        tasks: 1
        cpus_per_task: 1
        mem_mb: 24000

    soupx:
        nodes: 1
        tasks: 1
        cpus_per_task: 1
